before:
  hooks:
    - go mod download

gomod:
  proxy: true

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ldflags:
     - -s -w -X main.VERSION={{.Version}}

universal_binaries:
- replace: false

archives:
- replacements:
    darwin: macOS
    amd64: x64
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - name: scmpuff
    description: Adds numbered shortcuts for common git commands.
    homepage: https://mroth.github.io/scmpuff/
    license: MIT
    tap:
      owner: mroth
      name: homebrew-tap
    test: |
      ENV["e1"] = "abc"
      assert_equal "abc", shell_output("#{bin}/scmpuff expand 1").strip

changelog:
  skip: true
